title: Bruno G. Tavares's home page
email: devbruno78@gmail.com
description: >
  My projects page
baseurl: ""
url: "http://127.0.0.1:4000/"
# Build Settings

collections:
  projects:
    output: true
  other-projects:
    output: true

sass:
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM
