title: Bruno G. Tavares's home page
email: devbruno78@gmail.com
description: >
  Bruno G. Tavares's page
baseurl: ""
url: "http://bruno78.github.io"
# Build Settings

collections:
  projects:
    output: true

sources:
  - _assets/css
  - _assets/javascripts
  
gems:
  - jekyll-assets

markdown: kramdown
kramdown:
  input: GFM
