title: Bruno G. Tavares's home page
email: devbruno78@gmail.com
description: >
  Bruno G. Tavares's page
baseurl: ""
url: "http://bruno78.github.io"
# Build Settings

collections:
  projects:
    output: true
  other-projects:
    output: true

sass:
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM
